### ISSUE TITLE
Errors in the documentation

### ISSUE THREAD

**Issue by carlhye** [JensenNick/huawei_solar_eflr#1]
Hi - great project!

I've gone over the documentation and found some errors the confused me.

## 2.1 Tariff Export Sensor
The sensor you suggest to create in configuration.yaml is already included in the `huawei_solar_input.yaml` package, and it should not be needed to copy it to the config file.

## 2.3 Electricity Feed Automations

> Copy the custom automations from the file "1_electricity_feed_automations.yaml" to your automations.yaml file.
>
>Link to the power sensors [1_electricity_feed_automations.yml] https://github.com/JensenNick/huawei_solar_eflr/blob/main/1_electricity_feed_automations.yml)

The automation is included in `huawei_solar_eflr.yaml` and should not be added to the general automations file.
Also, the file you're linking to is 404 😅

**Comment by JensenNick** [comment]
@carlhye I know. You've caught me in the middle of transforming what was just a file with yaml-code into a package. I was first hoping to include more useful automations, but I'm also experimenting with Node-Red at the moment. I probably should have highlighted this in the README.
