### ISSUE TITLE
Automatically pull tariffs from integration

### ISSUE THREAD

**Issue by carlhye** [JensenNick/huawei_solar_eflr#2]
### Feature request: dynamic tariffs

As you already suggest using the Energi Data Service integration, it should be possible to pull the tariffs from the attributes of this integration, since it already includes them and you set your provider when configuring it.

Tarriffs in the Energi Data Service integration:
![image](https://github.com/JensenNick/huawei_solar_eflr/assets/82280057/22e31f4e-7fba-4410-98c5-d9f71069bd0c)

This would avoid the need to have to customise the `sensor.tariff_export` in the `huawei_solar_input.yaml` file.
Since tariffs in many cases are also dynamic, the current sensor would not provide the most accurate tariffs anyway.

**Comment by JensenNick** [comment]
@carlhye I do not think so. The tariffs included in EDS are all tariff on import (purchase) not export (sale). In DK these tariffs are not the same. Not 100% sure how it is in the other countries that EDS cover, though.
